services:

  db:
    image: postgres:17.5
    restart: always
    volumes: 
      - db_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - sysacad_network

  backend:
    image: sysacad:dev
    build:  .
    volumes:
      - .:/app  # only for development, not recommended for production
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - sysacad_network

networks:
  sysacad_network:
    name: sysacad_network

volumes:
  db_data:
    driver: local